### ISSUE TITLE
Is it possible to add custom event classes without customizing the Android SDK?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [mobfox/MobFox-Android-SDK#19]
Is it possible to add custom event classes without customizing the Android SDK?

If not, which is the easiest way to do it?

**Comment by michal-gecko** [comment]
Hi,
Actually you could try doing it without compiling the SDK yourself- just make sure that your custom event is in package com.adsdk.sdk.customevents. ,and it has proper name (someNetworkBanner or someNetworkFullscreen). Some additional instructions on creating custom events can be also found here: https://github.com/mobfox/MobFox-Android-SDK/wiki/Add-Custom-Events-(Advanced)

**Comment by adriano-di-giovanni** [comment]
Great,
I did it as my first try but I can't say it worked.

How can I be sure that my custom class has been call? Is it loggable?

Thanks in advance,
Adriano

**Comment by adriano-di-giovanni** [comment]
I'd like to stress that I read all docs at least twice but I can't get the custom event class to work or I can't get any evidence about it :)

**Comment by michal-gecko** [comment]
Hmm, we don't really log which custom event class is called... But you can simply add some LogCat messages (or just use debugger) in your custom classes to see if they are called properly.

**Comment by adriano-di-giovanni** [comment]
It works.
I created custom event classes in com.adsdk.sdk.customevents package of my projects. I don't know why it didn't work the first time.

Thanks, @michal-gecko
