### ISSUE TITLE
Change Play Services dependency to only Play Services Ads API

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-Android-SDK#20]
Hi @nabriski 
Creating a new issue here so that I'm notified when it's closed.

According to [this guide](https://developer.android.com/google/play-services/id.html) you only need **com.google.android.gms:play-services-ads** dependency to fetch the Ad ID. This would significantly reduce the apk size compared to adding all the APIs.

Hope you can implement this soon. Thanks!

**Comment by nabriski** [comment]
Ok, thanks, we'll test it. If that's all there is to it, will be part of our next release.
