### ISSUE TITLE
AdMob memory leak

### ISSUE THREAD

**Issue by ghost** [mobfox/MobFox-Android-SDK#24]
AdMob causes a memory leak when the activity is destroyed. As noted in [this SO answer](http://stackoverflow.com/a/35121180), the leak doesn't happen if application context is provided.
However, in [one of the comments](https://stackoverflow.com/questions/33509371/adview-causes-memory-leak/35121180#comment62529116_35121180) it is mentioned that mediation could take a hit. 
So, could you please tell me if MobFox's adapter would suffer in case I use application context while creating an AdView?

**Comment by asafgaber** [comment]
you can use the application context for our admob adapter. please take the latest release 2.0.6 as it has some bug fixes and go through our documentation to see how to initiate our adapter class
