### ISSUE TITLE
MobFox version 2+ cause ANR

### ISSUE THREAD

**Issue by pongpatr** [mobfox/MobFox-Android-SDK#25]
MobFox library version 2+ cause ANR when press home then back to our app.

The issue is gone if we downgrade library to 1.5.8

ANR track below
https://drive.google.com/file/d/0ByeaAjxOM6FBZ3hzTEJYZXhsRWc/view?usp=sharing

**Comment by nabriski** [comment]
Hi, can you please share your integration code?

**Comment by pongpatr** [comment]
We use MobFox as a mediation network in AdMob.

The only code we add is at AndroidManifest.xml
<activity android:name="com.mobfox.sdk.interstitialads.InterstitialActivity" />

**Comment by nabriski** [comment]
Can you please share the code you use to load the AdMob ad + your layout xml for the ad?
thanks

**Comment by pongpatr** [comment]
Please note that we are using
compile 'com.google.firebase:firebase-ads:9.0.2'

Below is requested code snippet

```
<LinearLayout
    android:id="@+id/defaultBanner"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical" />

mBannerContainer = (LinearLayout) mActivity.findViewById(R.id.defaultBanner);

AdRequest.Builder adRequestBuilder = new AdRequest.Builder();
AdRequest adRequest = adRequestBuilder.build();

mAdView = new AdView(mActivity);
mAdView.setAdSize(AdSize.SMART_BANNER);
mAdView.setAdUnitId(Const.ADMOB_BANNER_ID);
mAdView.loadAd(adRequest);

mBannerContainer.removeAllViews();
mBannerContainer.addView(mAdView);
```

**Comment by asafgaber** [comment]
Hi,
Thanks for the implementation code, very helpful.
find fixed adapter here:
http://static.starbolt.io/MobFox-Android-AdMob-Adapter-Smart.jar
its not a part of the release yet

take notice that admob should initiate the 
com.mobfox.adapter.MobFoxAdapter class for banner and interstitial when you create the custom network
