### ISSUE TITLE
MobFox banner take whole screen when load

### ISSUE THREAD

**Issue by pongpatr** [mobfox/MobFox-Android-SDK#26]
MobFox banner take whole screen when load

Note: We use MobFox as a mediation network in AdMob.

Library version 2.0.4
https://drive.google.com/file/d/0ByeaAjxOM6FBQ2ZfeU5MalU2a3c/view?usp=sharing

**Comment by nabriski** [comment]
Do you mean you use it for an interstitial? or as banner of what size?
thanks

**Comment by pongpatr** [comment]
The above attachment is taken after banner load finish.

We use AdMob smart banner size (AdSize.SMART_BANNER)

**Comment by nabriski** [comment]
Only thing I can think of is that the smart banner size is calculated incorrectly, can you please attach the app log?
thanks

**Comment by asafgaber** [comment]
We released a fix of the admob adapter that should take care of this. Please get the latest adapter (take a look at the doc there are changes in the classes names) and try again, if the problem still continues please write 'MobFox' in android monitor and send us the log. thanks

**Comment by pongpatr** [comment]
Thank you for quick update. We will test this throughout our test devices and will let you know :)

**Comment by pongpatr** [comment]
The ad still take the whole screen on Android v17

**Comment by nabriski** [comment]
Hi, can you please attach the app log to this issue?
Thanks

**Comment by pongpatr** [comment]
06-22 13:54:34.019 29921-29921/com.example.debug W/Ads: Server parameters: {"class_name":"com.mobfox.adapter.MobFoxAdapter","gwhirl_share_location":"1","label":"MobFox","parameter":"fe96717d9875b9da4339ea5367eff1ec"}
06-22 13:54:34.029 29921-29921/com.example.debug D/MobFoxAdapter: MobFoxAdapter constructor
06-22 13:54:34.029 29921-29921/com.example.debug D/MobFoxAdapter: MobFox AdMob Adapter >> init banner w:320 h:50
                                                                             adSize: 384x50_as
06-22 13:54:34.079 29921-29921/com.example.debug D/MobFoxWebView: mobfox webview init
06-22 13:54:34.089 29921-29921/com.example.debug I/dalvikvm: Could not find method android.webkit.WebResourceRequest.getUrl, referenced from method com.mobfox.sdk.webview.MobFoxWebViewClient.onReceivedError
06-22 13:54:35.811 29921-29921/com.example.debug D/MobFoxWebView: SDK load
06-22 13:54:35.811 29921-29921/com.example.debug D/MobFoxBanner: init done for GET_LAYOUT
06-22 13:54:35.811 29921-29921/com.example.debug D/MobFoxBanner: adspace_width: 320
                                                                            adspace_height: 50
06-22 13:54:35.851 29921-29921/com.example.debug D/MobFoxUtils: /data/data/com.example.debug/files/mobfox-dmp-bundle: open failed: ENOENT (No such file or directory)
06-22 13:54:35.851 29921-29921/com.example.debug D/MobFoxBanner: bundle id: com.example.debug
06-22 13:54:36.902 29921-29921/com.example.debug D/MobFoxWebView: page load started: file:///data/data/com.example.debug/cache/
06-22 13:54:36.902 29921-29921/com.example.debug D/MobFoxWebView: Loading done at 100
06-22 13:54:36.902 29921-29921/com.example.debug D/MobFoxBanner: init done for LOAD_JS
06-22 13:54:37.573 29921-29921/com.example.debug D/MobFoxWebView: ready
06-22 13:54:37.573 29921-29921/com.example.debug D/MobFoxWebView: notify onReady
06-22 13:54:37.573 29921-29921/com.example.debug D/MobFoxWebView: onReady
06-22 13:54:37.583 29921-29921/com.example.debug D/MobFoxBanner: o_andadvid: 055d9646-2b76-4d0f-9503-6a638d9795eb
06-22 13:54:37.583 29921-29921/com.example.debug D/MobFoxBanner: init done for GET_ADVERTISING_ID
06-22 13:54:37.833 29921-29921/com.example.debug D/MobFoxBanner: init done for GET_LOCATION
06-22 13:54:37.843 29921-29921/com.example.debug D/MobFoxBanner: init done
06-22 13:54:37.843 29921-29921/com.example.debug D/MobFoxBanner: make done
06-22 13:54:37.853 29921-29921/com.example.debug D/MobFoxBanner: request params: {"adspace_width":320,"adspace_strict":0,"adFormat":"banner","auto_pilot":true,"secure":false,"debug":"","sub_bundle_id":"com.example.debug","skip":"","type":"waterfall","autoplay":"true","v":"Core_2.0.6","banner_pos":1,"start_muted":false,"s":"fe96717d9875b9da4339ea5367eff1ec","adspace_height":50,"rt":"android_app","o_andadvid":"055d9646-2b76-4d0f-9503-6a638d9795eb"}
06-22 13:54:38.374 29921-29921/com.example.debug D/MobFoxConsole: CONSOLE>>> {"data":"{\"waterfalls\":{\"banner\" : [{\"name\":\"banner\",\"prob\":1.0},{\"name\":\"nativeFormat\",\"prob\":0.0}],\"interstitial\":[{\"name\":\"video\",\"prob\":0.8},{\"name\":\"banner\",\"prob\":1.0},{\"name\":\"nativeFormat\",\"prob\":0.0}]}}","handlerName":"setWaterfallsJson"}
06-22 13:54:38.374 29921-29921/com.example.debug D/MobFoxConsole: CONSOLE>>> {"data":"{\"adspace_width\":320,\"adspace_strict\":0,\"adFormat\":\"banner\",\"auto_pilot\":true,\"secure\":false,\"debug\":\"\",\"sub_bundle_id\":\"com.example.debug\",\"skip\":\"\",\"type\":\"waterfall\",\"autoplay\":\"true\",\"v\":\"Core_2.0.6\",\"banner_pos\":1,\"start_muted\":false,\"s\":\"fe96717d9875b9da4339ea5367eff1ec\",\"adspace_height\":50,\"rt\":\"android_app\",\"o_andadvid\":\"055d9646-2b76-4d0f-9503-6a638d9795eb\"}","handlerName":"loadAd"}
06-22 13:54:39.185 29921-29921/com.example.debug D/MobFoxWebView: data >>> :{"type":"banner","ad":{"encoded":true,"options":{"enforceSize":false,"skip":false,"auto_pilot":true},"params":{"adspace_width":320,"c_customevents":"1","adspace_strict":0,"m":"live","debug":"","sub_bundle_id":"com.example.debug","autoplay":"true","imp_secure":0,"v":"Core_2.0.6","u":"Mozilla\/5.0 (Linux; U; Android 4.2.2; en-us; Nexus 4 Build\/JDQ39) AppleWebKit\/534.30 (KHTML, like Gecko) Version\/4.0 Mobile Safari\/534.30","banner_pos":1,"dev_js":1,"start_muted":false,"c_mraid":2,"s":"fe96717d9875b9da4339ea5367eff1ec","adspace_height":50,"rt":"android_app","o_andadvid":"055d9646-2b76-4d0f-9503-6a638d9795eb"},"request":{"clickurl":{"__cdata":"http:\/\/my.mobfox.com\/exchange.click.php?h=689d4a0f65b2275a55f18b384e55f852"},"_type":"textAd","scale":"no","skippreflight":"yes","urltype":"link","clicktype":"safari","htmlString":{"__cdata":"PGJvZHkgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO21hcmdpbjowO3BhZGRpbmc6MDsiPjxhIGhyZWY9Imh0dHA6Ly9teS5tb2Jmb3guY29tL2V4Y2hhbmdlLmNsaWNrLnBocD9oPTY4OWQ0YTBmNjViMjI3NWE1NWYxOGIzODRlNTVmODUyIiB0YXJnZXQ9Il9zZWxmIj48aW1nIHNyYz0iaHR0cDovL2NyZWF0aXZlMmNkbi5tb2Jmb3guY29tL2JmYzEzNmI4ZWM1YjdlY2IwMWUxMjA2ZTIwY2VkMDNkLmdpZiIgYm9yZGVyPSIwIi8+PC9hPjxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vcnRiLmltcHJlc3Npb24ucGl4ZWwucGhwP3JpZD03NTcyOTMwZjg1MWQyZWNkYjk2MGQ1NjQzZTg2OTAwMyZwcmljZT0wLjI0OSIvPjxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vZXhjaGFuZ2UucGl4ZWwucGhwP2g9Njg5ZDRhMGY2NWIyMjc1YTU1ZjE4YjM4NGU1NWY4NTIiLz48c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+ZG9jdW1lbnQud3JpdGUoJzxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vZXhjaGFuZ2UucGl4ZWwucGhwP2g9Njg5ZDRhMGY2NWIyMjc1YTU1ZjE4YjM4NGU1NWY4NTImdGVzdD0xIi8+Jyk7PC9zY3JpcHQ+PC9ib2R5Pg=="},"refresh":"30"}},"customEvents":[]}
06-22 13:54:39.185 29921-29921/com.example.debug D/MobFoxBanner: on ad response
06-22 13:54:39.185 29921-29921/com.example.debug D/MobFoxBanner: mobFox bannerEvent
06-22 13:54:39.185 29921-29921/com.example.debug D/MobFoxBanner: banner event load MobFox ad
06-22 13:54:39.195 29921-29921/com.example.debug D/MobFoxBanner: banner loaded
06-22 13:54:39.195 29921-29921/com.example.debug D/MobFoxAdapter: MobFox AdMob Adapter >> Banner loaded
06-22 13:54:39.195 29921-29921/com.example.debug D/MobFoxBanner: pixel is null
06-22 13:54:39.525 29921-29921/com.example.debug D/MobFoxConsole: CONSOLE>>> {"data":"{\"type\":\"banner\",\"ad\":{\"encoded\":true,\"request\":{\"clickurl\":{\"__cdata\":\"http:\\/\\/my.mobfox.com\\/exchange.click.php?h=689d4a0f65b2275a55f18b384e55f852\"},\"scale\":\"no\",\"_type\":\"textAd\",\"urltype\":\"link\",\"skippreflight\":\"yes\",\"htmlString\":{\"__cdata\":\"PGJvZHkgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyO21hcmdpbjowO3BhZGRpbmc6MDsiPjxhIGhyZWY9Imh0dHA6Ly9teS5tb2Jmb3guY29tL2V4Y2hhbmdlLmNsaWNrLnBocD9oPTY4OWQ0YTBmNjViMjI3NWE1NWYxOGIzODRlNTVmODUyIiB0YXJnZXQ9Il9zZWxmIj48aW1nIHNyYz0iaHR0cDovL2NyZWF0aXZlMmNkbi5tb2Jmb3guY29tL2JmYzEzNmI4ZWM1YjdlY2IwMWUxMjA2ZTIwY2VkMDNkLmdpZiIgYm9yZGVyPSIwIi8+PC9hPjxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vcnRiLmltcHJlc3Npb24ucGl4ZWwucGhwP3JpZD03NTcyOTMwZjg1MWQyZWNkYjk2MGQ1NjQzZTg2OTAwMyZwcmljZT0wLjI0OSIvPjxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vZXhjaGFuZ2UucGl4ZWwucGhwP2g9Njg5ZDRhMGY2NWIyMjc1YTU1ZjE4YjM4NGU1NWY4NTIiLz48c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+ZG9jdW1lbnQud3JpdGUoJzxpbWcgc3R5bGU9InBvc2l0aW9uOmFic29sdXRlOyBsZWZ0OiAtMTAwMDBweDsiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIHNyYz0iaHR0cDovL215Lm1vYmZveC5jb20vZXhjaGFuZ2UucGl4ZWwucGhwP2g9Njg5ZDRhMGY2NWIyMjc1YTU1ZjE4YjM4NGU1NWY4NTImdGVzdD0xIi8+Jyk7PC9zY3JpcHQ+PC9ib2R5Pg==\"},\"clicktype\":\"safari\",\"refresh\":\"30\"},\"params\":{\"adspace_width\":320,\"adspace_strict\":0,\"c_customevents\":\"1\",\"debug\":\"\",\"m\":\"live\",\"sub_bundle_id\":\"com.example.debug\",\"autoplay\":\"true\",\"v\":\"Core_2.0.6\",\"imp_secure\":0,\"banner_pos\":1,\"u\":\"Mozilla\\/5.0 (Linux; U; Android 4.2.2; en-us; Nexus 4 Build\\/JDQ39) AppleWebKit\\/534.30 (KHTML, like Gecko) Version\\/4.0 Mobile Safari\\/534.30\",\"start_muted\":false,\"dev_js\":1,\"s\":\"fe96717d9875b9da4339ea5367eff1ec\",\"c_mraid\":2,\"adspace_height\":50,\"rt\":\"android_app\",\"o_andadvid\":\"055d9646-2b76-4d0f-9503-6a638d9795eb\"},\"options\":{\"skip\":false,\"enforceSize\":false,\"auto_pilot\":true}},\"customEvents\":[]}","handlerName":"renderAd","callbackId":"JAVA_CB_1_13528"}
06-22 13:54:39.525 29921-29921/com.example.debug D/MobFoxConsole: CONSOLE>>> click url: [object Object]
06-22 13:54:39.525 29921-29921/com.example.debug D/MobFoxWebView: Loading done at 100
06-22 13:54:39.535 29921-29921/com.example.debug D/MobFoxBanner: render response:

**Comment by pongpatr** [comment]
This kind of issue is extremely serious because once ad take the whole screen user cannot do anything.

**Comment by nabriski** [comment]
Yes, we also want to solve this, but are still unable to replicate this on our test devices. Any chance you can send me a link of the build to itamar.n@matomy.com? thanks

**Comment by wharnisch** [comment]
Problem occurs whenever banner view uses WRAP_CONTENT for its height in LayoutParams. It seems that the banner does not calculate its preferred hight correctly but instead in this case behaves as if FILL_PARENT was specified. Whenever a height in pixels is used problem does not occur. Problem also does not occur in versions 1.x.x, so it definitely does not occur with version 1.5.8.

**Comment by pongpatr** [comment]
Thank you for the update. We could not specify exact hight for its container as the hight of SMART_BANNER size may vary for different devices.

**Comment by nabriski** [comment]
Well, if that's the problem, we can probably release a fix this week.

**Comment by asafgaber** [comment]
Hi,
you can find the fixed adapter here
http://static.starbolt.io/MobFox-Android-AdMob-Adapter-Smart.jar
its not a part of the release yet 

take notice that admob should initiate the 
com.mobfox.adapter.MobFoxAdapter class for banner and interstitial when you create the custom network
