### ISSUE TITLE
No ads without location permission

### ISSUE THREAD

**Issue by wharnisch** [mobfox/MobFox-Android-SDK#27]
No banner ads are loaded if app does not have permission ACCESS_FINE_LOCATION. So this permission seems to be mandatory. Even worse: If the manifest contains this permission but user did not grant this permission the ad itself asks the user for the permission. It is not a good idea that an app needs this privacy related permission just because of the ads.

Solution: Banner should have be a method like "setUseLocation(boolean)" to disable this behavior.

 Also READ_PHONE_STATE permission should not be mandatory.

**Comment by nabriski** [comment]
Hi,
Which version of the SDK are you using and on which Android version did you test? I thought we removed the dependency on ACCESS_FINE_LOCATION (although it's part of the documentation).

Thanks

**Comment by wharnisch** [comment]
We tested with SDK version 2.0.7 yesterday. We have seen the problem where an action of the banner (probably requesting location) leading to asking the user for permission in Android 6, as only Android 6 and up supports this. We found the problem that no banner ads are being loaded in the case that the app does not have permission ACCESS_FINE_LOCATION in Android 4.4 and I think in Android 6 also. A method "setUseLocation(boolean)" where a call with "false" disables requesting of location by the banner at all could solve both problems. A method to globally disable requesting of location for all banners would be even better, because this also could be used with mediation.

Regards

**Comment by nabriski** [comment]
Hi,

Yes, we have this on iOS, and as Android 6 behaves similarly we will add this global setter,
As for the permission, we were hoping to just gracefully detect the permission is missing and move on. Will recheck.
I will close this issue when we take care of this so you'll be notified.

**Comment by asafgaber** [comment]
Hi,

Fix on 2.0.8 version
