### ISSUE TITLE
com.mobfox.adapter.MobFoxAdapter implements wrong interface

### ISSUE THREAD

**Issue by aiurlano** [mobfox/MobFox-Android-SDK#28]
In AdMob mediation, when using MobFox, the sdk tries to load the class com.mobfox.adapter.MobFoxAdapter but fails with this error:
W Ads : Could not instantiate mediation adapter: com.mobfox.adapter.MobFoxAdapter (not a valid adapter).

This happens because MobFoxAdapter is currently implementing the interface CustomEventBanner which is for custom event adapter and not for integrated mediation adapters
Instead it should be implementing the interface MediationBannerAdapter

**Comment by nabriski** [comment]
Hi,
We'll look into this on Sunday and will post updates on this issue thread.
Thanks

**Comment by asafgaber** [comment]
We are waiting on admob to verify out new adapter with their new interface. we'll release it asap
thanks
