### ISSUE TITLE
setGetLocation in static method (was 'Ad independently asks user of app for ACCESS_FINE_LOCATION permission on Android 6')

### ISSUE THREAD

**Issue by wharnisch** [mobfox/MobFox-Android-SDK#29]
This has not been fixed with 2.0.9, just tested.

If the manifest contains this permission but user did not grant this permission the ad independently asks the user for this permission. It is not a good idea that a user has to grant this privacy related permission just because of the ads.
Possible Solutions:
(a) On Android 6+, check if user has granted this permission. Do **not** try to query location if user has not granted this permission.
(b) Provide a method like in iOS to globally disable usage of location services for banners
Solution (a) would be smarter!

**Comment by nabriski** [comment]
It's not static yet, but we did add to banner:

``` java
 public void setGetLocation(boolean getLocation);
```

**Comment by wharnisch** [comment]
Just tested, works perfectly, thank you, good work!
I suppose, setgetLocation just affects the banner object it is called for. So an additional static (global) version of this as mentioned would be very nice and especially useful for mediation where the the adapter creates banner objects and one does not have access to this objects to call setGetLocation.

**Comment by nabriski** [comment]
Yes, we wanted to add something quick and simple. We will move it to a static method in the next version or so. I'm leaving this issue open until we do.

**Comment by nabriski** [comment]
now we have:

``` java
Banner.setGetLocation(false) 
```
