### ISSUE TITLE
Publish 2.1.3 release, gradle integration instructions break build.

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#33]
Your gradle integration instructions tell us to use version `2.1.3`, however, it seems you updated the instructions but didn't publish the `2.1.3` release.

`compile 'com.github.mobfox:MobFox-Android-SDK-Core:2.1.3'`

Current solution, use `2.1.2`

**Comment by nabriski** [comment]
Hi, will check this tomorrow morning, you can also use the jar installation for now as well.
Strange, the tag does exist.

**Comment by nabriski** [comment]
yes, you are correct about the jar release (latest version), fixed it. Gradle released will fixed tomorrow.

**Comment by gubatron** [comment]
Thank you!
