### ISSUE TITLE
No Source Code.

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#34]
Your website advertises your SDK as OpenSource, however, I have to decompile your classes in order to see what's going on. I can't find things like `InterstitialAd.java` for example.

Where is that code? You don't want the FTC nailing you for misleading advertising.

All I see is the .jar releases.

**Comment by gubatron** [comment]
<img width="285" alt="screen shot 2016-08-08 at 3 56 14 pm" src="https://cloud.githubusercontent.com/assets/163977/17497742/a92b0754-5d80-11e6-83b8-18bac36f46c4.png">

**Comment by gubatron** [comment]
<img width="1272" alt="screen shot 2016-08-08 at 3 57 12 pm" src="https://cloud.githubusercontent.com/assets/163977/17497780/ce30fdce-5d80-11e6-8755-7b4f2858f686.png">

Not a single source file.

**Comment by nabriski** [comment]
Hi,

The new version of the SDK (Core) is a complete rewrite and is close sourced. The website is out of date and will be fixed.

Thanks

**Comment by gubatron** [comment]
Thanks!

CC: @paulinka
