### ISSUE TITLE
Q: Is there a way to suppress asking for the user's location when loading an ad?

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#35]
I'm loading an interstitial on the UI thread, but despite me not adding
`ACCESS_FINE_LOCATION` on the manifest, MobFox still asks for it, is there a way to skip this, or is this mandatory?

We have several reasons not to ask our users for fine location:
- Privacy
- Our app has nothing to do with the user's location
- We want to be energy efficient and not have to use the GPS, everytime our app starts to drain more battery we see our installation numbers drop.

**Comment by gubatron** [comment]
hmm, perhaps with reflection I can remove the `BannerInitTasks.Tasks.GET_LOCATION`?
wouldn't want to hack like that.

**Comment by gubatron** [comment]
I was trying this, but no go:

``` java
interstitialAd = new InterstitialAd(activity);
final BannerInitTasks initTasks = interstitialAd.getBanner().getInitTasks();
try {
    final Field tasksField = initTasks.getClass().getDeclaredField("tasks");
    tasksField.setAccessible(true);
    Map<BannerInitTasks.Tasks, Boolean> tasks = (Map<BannerInitTasks.Tasks, Boolean>) tasksField.get(initTasks);
    if (tasks != null) {
        tasks.remove(BannerInitTasks.Tasks.GET_LOCATION);
        LOG.info("Removed GET_LOCATION task");
   }
} catch (Throwable t) {
    t.printStackTrace();
}

interstitialAd.setInventoryHash(Constants.MOBFOX_INVENTORY_HASH);
interstitialAd.setListener(interstitialAdListener);

 // make sure this happens on the UI thread.
Handler handler = new Handler(activity.getMainLooper());
handler.post(new Runnable() {
    @Override
    public void run() {
       interstitialAd.load();
    }
});
```

Also, if the user denies permission it asks over and over, and then I got another permission screen to draw on screen.

Are there any settings available to be less aggressive?

**Comment by nabriski** [comment]
yes, there is (static method):

``` java
Banner.setGetLocation(false)
```

We didn't document it because we assumed that in order to get better CPMs most publishers will want the location. With Android 6 permission prompts this is changing. Will have to rethink.

**Comment by gubatron** [comment]
Thank you so much!

**Comment by gylippus** [comment]
@nabriski has `Banner.setGetLocation(false)` been tested in the latest Android .jar ? 

I'm getting errors now that I've updated:

```
error: cannot find symbol
    Banner.setGetLocation(false);
    ^
symbol:   method setGetLocation(boolean)
```

**Comment by nabriski** [comment]
Hi,
Yes, we gave it a slight overhaul. You can remove this line, this method was removed and now it's false by default.
See here if you want to enable it:
https://github.com/mobfox/MobFox-Android-SDK#location

**Comment by gylippus** [comment]
Ah, thanks even better. I realized I was actually compiling the wrong
version number anyways is what my issue was.
