### ISSUE TITLE
No InterstitialAdListener::onBackPressed() event handler available.

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#36]
None of these methods get invoked when the Android back button is pressed while displaying an interstitial ad. 

```
public interface InterstitialAdListener {
    void onInterstitialLoaded(InterstitialAd var1);

    void onInterstitialFailed(InterstitialAd var1, Exception var2);

    void onInterstitialClosed(InterstitialAd var1);

    void onInterstitialFinished();

    void onInterstitialClicked(InterstitialAd var1);

    void onInterstitialShown(InterstitialAd var1);
}
```
### Should I extend InterstitialAd and add my callback?

Luckily I see that InterstitialAd isn't final so I believe I can invoke a new method on my InterstitialAdListener implementation, but perhaps there's already another way to catch this event.

**Comment by nabriski** [comment]
Hi,
Sure, if it passes our testing, we'll add it to our code base happily.

**Comment by gubatron** [comment]
so I can take that that as it is right now, there's no way (unless I hack) to get the `onBackPressed()` from the interstitial.

**Comment by gubatron** [comment]
(and wouldn't be able to add it to your code base, the .java source code is closed 😭 )

**Comment by nabriski** [comment]
yes, we don't have it right now.
You cannot commit the code but if you send me the files I'll diff and merge them into the project, if that's helpful to you.

Thanks

**Comment by nabriski** [comment]
We can add this functionality ourselves, we'll take a lot at it on Sunday.

**Comment by gubatron** [comment]
any progress on this callback?

**Comment by nabriski** [comment]
Hi, we decided to put add it to our back log but not implement this for the next few releases as we saw this not a standard call for ad SDKs.
