### ISSUE TITLE
Auto opening ads

### ISSUE THREAD

**Issue by aiurlano** [mobfox/MobFox-Android-SDK#37]
Hello. We have reports of ads opening by themselves without user clicking on them.

We suspect they might be coming from MobFox.
Will Banner.setDev_js(0) help us in preventing this kind of ads?

Unfortunately we don't have any logs, just some screenshots.

Thanks

![screenshot_2016-08-12-09-45-35](https://cloud.githubusercontent.com/assets/353288/17642745/a0de2d76-6152-11e6-8d67-6833b403f575.png)

**Comment by nabriski** [comment]
Hi, yes it should but you will lose some demand too so your CPM may drop. Worth a try.

This behavior should be blocked as I don't allow modals. If the ad was able to do it on a recent version, I will add a more aggressive setting that is less aggressive then the `Banner.setDev_js(0)` but should stop this behavior completely. Will try to release an update Sunday/Monday.

Also what is your inventory hash? we can try to scan your demand for this and block it. A log will make it more helpful, but we can try anyway.

**Comment by aiurlano** [comment]
Hello and thanks for looking into it.

I have sent the inventory hash to your email. We cannot reproduce it on our side and thus we have no log, sorry. We are also not 100% sure that this is coming from MobFox but as we are working toward sending you more traffic, I would be very happy to have a rock solid disable js feature in the sdk.
Annoying ads drive our users away. Any cpm drop we might see would definitely be better than any user drop.

Thanks!

**Comment by nabriski** [comment]
just make you are using the latest version

**Comment by shoval1** [comment]
Hi, in which days did you send traffic?

**Comment by aiurlano** [comment]
Hi. The Ad was shown on 12th August.

We are already using latest version (2.1.2). We'll publish soon an update with 2.1.3 and SetDevJS(0).

Thanks

**Comment by shoval1** [comment]
Hi,
We haven't succeed to find the demand source in these inset however we take a very serious view on these kind of advertisers. 
It is highly likely that other publishers will have reported this type of activity and been able to provide logs containing our impression beacons, and we will have blocked it.
Moving forward please provide the ad response of ads which you have an issue with and we will be able to identify and block the advertising in a quick and efficient manner.
