### ISSUE TITLE
Question: Is there a background thread running after the first Interstitial Load?

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#38]
Our app has a full shutdown feature, would like to know if there's any background threads than can be signalled to die so we can shutdown cleanly when the user desires.

**Comment by nabriski** [comment]
Hi,

We do not employ any bg threads at this time. This may change in the future, we'll post it in the release notes if it does.

**Comment by gubatron** [comment]
Thanks! This helps a lot to discard one shutdown issue we have now on our mobfox testing branch.
Cheers!

(If things change in the future, please include a `.shutdown()` method there)
