### ISSUE TITLE
BUG: onInterstitialClosed() called up to 7x when closing an interstitial

### ISSUE THREAD

**Issue by gubatron** [mobfox/MobFox-Android-SDK#39]
Boy has this bug caused me a lot of wasted time. For some reason, `onInterstitialClosed` gets called multiple times when dismissing an interstitial ad (when touching the X icon)

This was calling my listener logic multiple times thus screwing everything up.

Currently trying to solve either with concurrency tools, or somehow adding more logic to ignore these calls.

<img width="1083" alt="screen shot 2016-08-16 at 8 39 01 pm" src="https://cloud.githubusercontent.com/assets/163977/17722744/cba5b8ac-63f1-11e6-9c33-b9f215c4dbc3.png">

CC: @aldenml

**Comment by nabriski** [comment]
Hi,

Can you please post your integration code so we can try and reproduce the problem?

Thanks

**Comment by gubatron** [comment]
https://github.com/frostwire/frostwire/tree/mobfox2

**Comment by gubatron** [comment]
To test when the search screen appears, try touching the words "Search" five times to invoke an interstitial. See adb logcat for info.

**Comment by nabriski** [comment]
thanks, our Android dev will examine this

**Comment by asafgaber** [comment]
Hi, I pulled your project and debugged the mobfox activity. In your implementation, after the first interstitial shown and dismissed,  sometimes a new interstitial ad is called twice. That creates two instances that listen to the same broadcaster in the interstitial activity. Notice that onInterstitialClosed aggregates by 1 after each interstitial is close. You should take a look at that.  I created a fix in the MobFox SDK for this issue. its not formally released but you can get it from here:
compile 'com.github.mobfox:MobFox-Android-SDK-Core:2.1.3.1ci'
Asaf

**Comment by gubatron** [comment]
Thank you, will take a closer look.
