### ISSUE TITLE
unity error

### ISSUE THREAD

**Issue by stickylabdev** [mobfox/MobFox-Android-SDK#42]
below is the screenshoot
please see this error screemshoot
http://prnt.sc/ceymlg

**Comment by nabriski** [comment]
Hi,

Please paste here your Unity integration code. And also the app log, if possible.

Thanks

**Comment by stickylabdev** [comment]
damn ,,  you damt ,, that screenshoot contains the error log bro !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! please checkt!!!!!!!!!!!!!

**Comment by stickylabdev** [comment]
http://prnt.sc/ceymlg

**Comment by nabriski** [comment]
Yes, but we also need to see how you integrated our plugin. Please paste here the part of your code where you use our plugin.

Thanks

**Comment by stickylabdev** [comment]
i will paste bro ,,, i will paste !!!!!!!!!!!! please wait

2016-09-07 15:58 GMT+07:00 Itamar Nabriski notifications@github.com:

**Comment by nabriski** [comment]
please refer to the Unity Demo project:
https://github.com/mobfox/MobFox-Android-SDK-Core-Lib/tree/master/plugins/UnityDemo
