### ISSUE TITLE
Location is on by default when integrating with gradle

### ISSUE THREAD

**Issue by dakdroid** [mobfox/MobFox-Android-SDK#46]
compile 'com.github.mobfox:MobFox-Android-SDK-Core:3.0.6'

workaround:

1)`<meta-data tools:replace="android:value"  android:name="loc" android:value="false" />`

or 2) use the latest jar

**Comment by nabriski** [comment]
Hi,

Thanks.
We'll release a fix for this tomorrow (Sunday).

**Comment by nabriski** [comment]
fixed, see latest version
