### ISSUE TITLE
Location enabled by default

### ISSUE THREAD

**Issue by AndreiMorar** [mobfox/MobFox-Android-SDK#47]
Hi guys. The android.permission.ACCESS_FINE_LOCATION permission is enabled by default in the Manifest of your 3.1.0 version.

**Comment by nabriski** [comment]
Hi,
Sorry about that, crept into the release accidentally, just uploaded a fix:
https://github.com/mobfox/MobFox-Android-SDK/releases/tag/3.1.1
The developer responsible will be flayed.
