### ISSUE TITLE
1149 devices removed from Supported Android devices

### ISSUE THREAD

**Issue by AndreiMorar** [mobfox/MobFox-Android-SDK#48]
Hi guys. 
Here's an apk that I tried to publish in Alpha. It has the 3.0.0 version of your library: http://puu.sh/sOndB/7419d4045f.png

And here's the same exact build with the only difference being that I updated your library to 3.1.0: http://puu.sh/sOnnP/c44f33aa98.png

Ignoring that the location is enabled by default, why have 1149 devices been removed?

**Comment by nabriski** [comment]
This is not related to location?

**Comment by AndreiMorar** [comment]
Not sure, most probably. Let me check with the new 3.1.1 version and i'll get back to you. 5 minutes.

**Comment by AndreiMorar** [comment]
It seems the Location permission is still there. 

I'm building with 3.1.1. and the permission's still there. I cleaned the project and rebuilt ... :( Am I doing something wrong? :)

**Comment by nabriski** [comment]
strange, let me check

**Comment by nabriski** [comment]
was removed, still appears in the test proj permission, let me try to remove it as well.
also removed some other params that are not needed and were already removed previously.
here:
https://github.com/mobfox/MobFox-Android-SDK/releases/tag/3.1.2
please try again. If it still doesn't work I'll continue on this tomorrow morning.

**Comment by AndreiMorar** [comment]
Yup. It's fine now. The Supported Devices count is back to normal as well. Thanks. ;) Have a good night ....

**Comment by nabriski** [comment]
happy to help
