### ISSUE TITLE
MobFox SDK + Adapters duplicate problem

### ISSUE THREAD

**Issue by rafalswiech3** [mobfox/MobFox-Android-SDK#53]
Hi,

I've got problem with MobFox SDK + adapters for mediation networks.

I'm using latest Android Studio and latest SDK Tools. Also I'm using latest SDKs from MobFox + other networks

The problem is that when I add all the networks adapters I've got this error message: 

>Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
>com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/mobfox/adapter/MobFoxAdapter.class

If I remove StartApp and Smaato mobfox adapters from gradle then project build and run properly.

What can be wrong with that? Anyone can help me?

**Comment by nabriski** [comment]
Hi,

Can you please post here your gradle file?

Thanks

**Comment by rafalswiech3** [comment]
Hi,

I've removed Smaato adapter but I have still problem with StartApp.

This is error: 

>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
>com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: >com/startapp/android/publish/inappbrowser/a.class`

And this is my gradle file:

```
apply plugin: 'com.android.application'

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
        mavenCentral()
        maven {
            url "https://dl.bintray.com/supersonic/android-sdk"
        }
        maven { url "http://repo.appnext.com/" }
    }
}


android {
    compileSdkVersion 23
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "go.launcherex.theme.panda"
        minSdkVersion 16
        targetSdkVersion 18
        multiDexEnabled true
    }


    dexOptions {
        javaMaxHeapSize "4g"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/ASL2.0'
    }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.google.android.gms:play-services:+'
    compile 'com.github.mobfox:MobFox-Android-SDK-Core:3.2.5'
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile('com.mopub:mopub-sdk:4.12.0@aar') {
        transitive = true
    }
    compile 'com.adtoapp.android:adtoapp-banner:4.6.6'
    compile('com.appnext.sdk:appnext-sdk:2.+') // Mandatory
    compile 'com.google.android.gms:play-services-basement:10.2.0' // Mandatory
    compile 'com.google.android.gms:play-services-location:10.2.0' // Mandatory
    compile 'com.supersonic.sdk:mediationsdk:6.4.21@jar'
    compile 'com.google.firebase:firebase-ads:10.2.0'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile files('libs/MobFox-Android-AdColony-Adapter.jar')
    compile files('libs/MobFox-Android-AdMob-Adapter.jar')
    compile files('libs/MobFox-Android-Amazon-Adapter.jar')
    compile files('libs/MobFox-Android-AppLovin-Adapter.jar')
    compile files('libs/MobFox-Android-Chartboost-Adapter.jar')
    compile files('libs/MobFox-Android-Facebook-Adapter.jar')
    compile files('libs/MobFox-Android-Millenial-Adapter.jar')
    compile files('libs/MobFox-Android-MoPub-Adapter.jar')
    compile files('libs/MobFox-Android-Supersonic-Adapter.jar')
    compile files('libs/MobFox-Android-Vungle-Adapter.jar')
    compile files('libs/StartAppInApp-3.5.6.jar')
    compile files('libs/Woobi-Mobfox-1.0.0.jar')
    compile files('libs/applovin-sdk-6.4.2.jar')
    compile files('libs/chartboost.jar')
    compile files('libs/adcolony.jar')
    compile files('libs/javax.inject-1.jar')
    compile files('libs/dagger-2.7.jar')
    compile files('libs/vungle-publisher-adaptive-id-4.0.3.jar')
    compile project(':android-ad-sdk')

}
```

**Comment by asafgaber** [comment]
Hey,
Went over your gradle.build. Our package names for adapters are the same in some cases (startapp and smaato have the same adapter package name). We do it because publishers usually use one adapter to call us, or put us as primary and call other networks through their adapters.
We could change the package names if necessary, 
so why are you implementing us this way?

**Comment by rafalswiech3** [comment]
Ive implemented it this way because I need all supported networks via adapters to backfill if there is not fill from mobfox

**Comment by rafalswiech3** [comment]
Could you please update package names for smaato and startapp? 

My customer want to have all networks implemented but I cant do this without code changes in your adapters .jar files. 

Please let me know if so

**Comment by nabriski** [comment]
Hi,

Are you using MobFox as your main SDK, mediating to the other SDKs?
In that case we can put the custom events and the adapters in separate .jar files, solving this problem. I guess we better do this anyway.

**Comment by rafalswiech3** [comment]
Yes, mobfox is as main network

**Comment by nabriski** [comment]
ok, we'll fix this promptly. Will be part of next week's release.
I'll update this issue when we upload.

**Comment by asafgaber** [comment]
Hi,
We removed the conflicts. find startapp custom event jar [here](https://github.com/mobfox/MobFox-Android-SDK/blob/master/thirdPartyNetworks/Startapp/customEvents/MobFox-Android-Startapp-Custom.jar)
notice its called 'MobFox-Android-Startapp-Custom.jar'
same for [smaato](https://github.com/mobfox/MobFox-Android-SDK/blob/master/thirdPartyNetworks/Smaato/customEvent/MobFox-Android-Smaato-Custom.jar)
Thanks

**Comment by freakBoy008** [comment]
Hi,

Startapp adapter doesn't work for me if i want to add Startapp custom events. I'm always getting this on logcat;

`D/MobFoxBanner: iterator class not found exception`

Tried several versions of MobFox SDK, Startapp SDK. Also tried the old adapter for startapp and smaato. Also downgraded the target SDK to 25, but no success. Of course i've also done the custom event on MobFox control panel.

gradle dependencies:

> compile 'com.startapp:inapp-sdk:3.6.6'
    compile files('libs/MobFox-Android-Startapp-Custom.jar')

Manifest permissions:
<uses-permission android:name="android.permission.INTERNET"
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" 

Manifest entries under application tag:
<activity android:name="com.startapp.android.publish.ads.list3d.List3DActivity"
            android:theme="@android:style/Theme" 

        <activity android:name="com.startapp.android.publish.adsCommon.activities.OverlayActivity"
            android:theme="@android:style/Theme.Translucent"
            android:configChanges="orientation|keyboardHidden|screenSize" />

        <activity android:name="com.startapp.android.publish.adsCommon.activities.FullScreenActivity"
            android:theme="@android:style/Theme"
            android:configChanges="orientation|keyboardHidden|screenSize" />

        <service android:name="com.startapp.android.publish.common.metaData.PeriodicMetaDataService" 
       <service android:name="com.startapp.android.publish.common.metaData.InfoEventService" 
      <receiver android:name="com.startapp.android.publish.common.metaData.BootCompleteListener" 
          <intent-filter
                action android:name="android.intent.action.BOOT_COMPLETED" 
            /intent-filter
        /receiver

Best regards,
freakBoy008
