### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by sushrita** [mobfox/MobFox-Android-SDK#60]
I have added two ads one is  banner and other is interstitial ad  .
But I am facing timeout and other error in implementing the ads.

Log report 
 D/MobFoxWebView: mobfox webview init
 D/MobFoxUtils: read setting
 D/MobFoxBanner: dmp post completed
 W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
 W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
 W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
 D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxx","o_andadvid":"7ec77a58-d504-4fca-b296-c09da6d2c40f","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.example.packagename","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":0}
 D/MobFoxBanner: err
 D/MobFoxWebView: ready
 D/MobFoxWebView: mobfox webview init
 D/MobFoxUtils: read setting
 D/MobFoxBanner: dmp post completed
 D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"7ec77a58-d504-4fca-b296-c09da6d2c40f","type":"video","adFormat":"interstitial","autoplay":"true","skip":"true","debug":"","rt":"android_app","adspace_width":320,"adspace_height":480,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":7,"dev_dnt":0,"latitude":37.421998333333335,"longitude":-122.08400000000002}
 D/MobFoxInterstitial: on banner error
 D/MobFoxWebView: ready

If anyone can help then it will be very helpful for me.

**Comment by nabriski** [comment]
Hi,

You may get a timeout on the first attempt as sometimes not all resources are loaded yet.
If the timeout occurs consistently on every attempt, please post here more of the app log and we'll start to investigate.

Thanks,
Itamar

**Comment by sushrita** [comment]
Hi nabriski,
Yes the timeout error is showing with each ad I am implementing in code. so I am now posting the the detailed log below.

/MobFoxWebView: mobfox webview init
D/MobFoxUtils: read setting
D/MobFoxBanner: dmp post completed
 D/MobFoxBanner: google play error
 D/MobFoxBanner: on waterfalls fetch timeout
 W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
 W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
 W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":1}
 D/MobFoxBanner: err
 D/MobFoxWebView: ready
D/MobFoxWebView: mobfox webview init
 D/MobFoxUtils: read setting
 D/MobFoxBanner: dmp post completed
 D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"","type":"video","adFormat":"interstitial","autoplay":"true","skip":"true","debug":"","rt":"android_app","adspace_width":320,"adspace_height":480,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":7,"dev_dnt":1}
 D/MobFoxInterstitial: on banner error
D/MobFoxWebView: ready
 D/MobFoxConsole: CONSOLE>>> SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead., line: 0
D/MobFoxConsole: CONSOLE>>> This is not supported in browser version of superagent, line: 167
D/MobFoxWebView: data >>> :{"error":"xml not valid VAST or DAAST"}
 D/MobFoxInterstitial: on error xml not valid VAST or DAAST

**Comment by nabriski** [comment]
At least on interstitial the error is different:
```D/MobFoxInterstitial: on error xml not valid VAST or DAAST```
This means that a video call was made but something this is not a valid VAST was returned.
Can you please post here your interstitial integration code?

Thanks,
Itamar

**Comment by sushrita** [comment]
Code of interstitial 

>  InterstitialAd interstitial = new InterstitialAd(this);
> 
>         final Activity self = this;
> 
>         InterstitialAdListener listener = new InterstitialAdListener() {
>             @Override
>             public void onInterstitialLoaded(InterstitialAd interstitial) {
>                 Toast.makeText(self, "loaded", Toast.LENGTH_SHORT).show();
>                 //call show() to display the interstitial when its finished loading
>                 interstitial.show();
>             }
>             @Override
>             public void onInterstitialFailed(InterstitialAd interstitial, Exception e) {
>                 Toast.makeText(self, e.getMessage(), Toast.LENGTH_SHORT).show();
>             }
>             @Override
>             public void onInterstitialClosed(InterstitialAd interstitial) {
>                 Toast.makeText(self, "closed", Toast.LENGTH_SHORT).show();
>             }
>             @Override
>             public void onInterstitialFinished() {
>                 Toast.makeText(self, "finished", Toast.LENGTH_SHORT).show();
>             }
>             @Override
>             public void onInterstitialClicked(InterstitialAd interstitial) {
>                 Toast.makeText(self, "clicked", Toast.LENGTH_SHORT).show();
>             }
>             @Override
>             public void onInterstitialShown(InterstitialAd interstitial) {
>                 Toast.makeText(self, "shown", Toast.LENGTH_SHORT).show();
>             }
>         };
>         InterstitialAd.getLocation(true);
>         interstitial.setListener(listener);
>         interstitial.setType("video");
>         interstitial.setInventoryHash("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
>         interstitial.load();

**Comment by nabriski** [comment]
Hi,

I see you only want video demand, video demand has low fill. You can test it with our test video hash: ```80187188f458cfde788d961b6882fd53```. This will give you video fill every time.

Itamar

**Comment by sushrita** [comment]
So , how can I set video hash for test ?

**Comment by nabriski** [comment]
```interstitial.setInventoryHash("80187188f458cfde788d961b6882fd53");```

**Comment by sushrita** [comment]
okay  and about the banner ads it is constantly showing timeout error . Any suggestion?

**Comment by nabriski** [comment]
Can you please send me two consecutive banner request logs? (as much of the log as possible)

Thanks,
Itamar

**Comment by sushrita** [comment]
first log 
 D/MobFoxBanner: google play error
 W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
 W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
 W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
 D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":1,"latitude":37.421998333333335,"longitude":-122.08400000000002}
 D/MobFoxWebView: ready

2nd log

 D/MobFoxBanner: google play error
 W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
 W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
 W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
 D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":1,"latitude":37.421998333333335,"longitude":-122.08400000000002}
 D/MobFoxWebView: ready

**Comment by nabriski** [comment]
Hi,

Wait, are you creating the banner each time? I meant two requests on the same banner. Also I don't see the resulting error response.

Thanks,
Itamar

**Comment by sushrita** [comment]
D/MobFoxBanner: on waterfalls fetch timeout
W/System.err: at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
W/System.err: at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
this is the error .
No I am creating two different banners for each ad .

**Comment by nabriski** [comment]
This is just the waterfall, it should be able to continue anyway and fetch it next time. After the request, what response is returned?

**Comment by sushrita** [comment]
```
@Override
          public void onBannerError(View banner, Exception e) {
              Toast.makeText(getApplicationContext(), e.getMessage(), Toast.LENGTH_SHORT).show();
              Log.e("EXCEPTION",e.getMessage());
              e.printStackTrace();
          }
```
See for this overrided method i have used log with error message 
and getting a reply 
![timeout](https://user-images.githubusercontent.com/10562247/28618219-32df3ee2-7221-11e7-9543-74e416ca622d.PNG)

**Comment by nabriski** [comment]
If you call ```banner.load();``` again after the timeout, what do you get?

**Comment by sushrita** [comment]
FYI :I am using mediation with this account and I also downloaded your test app for testing from play store [https://play.google.com/store/apps/details?id=sdk.mobfox.com.appcore&hl=en
](url) with the hash it seems to generate no fill error . and I did try your `banner.load(); `method once again it's not working as well.

**Comment by nabriski** [comment]
Did you use our banner test hash of ```fe96717d9875b9da4339ea5367eff1ec```?

**Comment by sushrita** [comment]
yes i did test it in the app it is showing a toast as on banner error.

**Comment by nabriski** [comment]
Can you please send me the full log of calling ```banner.load()``` twice in a row (calling, waiting for error and then calling it again) with the test hash?

Thanks,
Itamar

**Comment by sushrita** [comment]
Test of Video Interstitial:

07-28 15:23:04.901 2836-2836/com.veblr.videomate D/MobFoxConsole: CONSOLE>>> SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead., line: 0
07-28 15:23:05.351 2836-2836/com.veblr.videomate D/MobFoxConsole: CONSOLE>>> This is not supported in browser version of superagent, line: 167
07-28 15:23:08.959 2836-2836/com.veblr.videomate D/MobFoxWebView: data >>> :{"cpm":50,"customEvents":[],"vasts":"W3siVkFTVCI6eyJBZCI6eyJJbkxpbmUiOnsiQWRTeXN0ZW0iOnsiX3ZlcnNpb24iOiIxLjAiLCJfX3RleHQiOiJNb2JGb3ggU1NQIn0sIkFkVGl0bGUiOnsiX19jZGF0YSI6Ik1vYkZveCBEaXJlY3QgU29sZCBWaWRlbyBDcmVhdGl2ZSJ9LCJJbXByZXNzaW9uIjpbeyJfX2NkYXRhIjoiaHR0cDovL3Rva3lvLW15Lm1vYmZveC5jb20vZXhjaGFuZ2UucGl4ZWwucGhwP2g9YTY2OTUxZGRkMjI1NmFkYjJlYmI5ZTUxOWFmNTg0NzMifSx7Il9fY2RhdGEiOiJodHRwOi8vdG9reW8tbXkubW9iZm94LmNvbS9leGNoYW5nZS5waXhlbC5waHA\/aD1hNjY5NTFkZGQyMjU2YWRiMmViYjllNTE5YWY1ODQ3MyZ0ZXN0PTEifV0sIkNyZWF0aXZlcyI6eyJDcmVhdGl2ZSI6eyJMaW5lYXIiOnsiRHVyYXRpb24iOiIwMDowMDowNyIsIlRyYWNraW5nRXZlbnRzIjp7IlRyYWNraW5nIjp7Il9ldmVudCI6InN0YXJ0IiwiX190ZXh0IjoiaHR0cDovL3Rva3lvLW15Lm1vYmZveC5jb20vc2VuZGNvb2tpZS5waHAifX0sIlZpZGVvQ2xpY2tzIjp7IkNsaWNrVGhyb3VnaCI6Imh0dHA6Ly90b2t5by1teS5tb2Jmb3guY29tL2V4Y2hhbmdlLmNsaWNrLnBocD9oPWE2Njk1MWRkZDIyNTZhZGIyZWJiOWU1MTlhZjU4NDczIn0sIk1lZGlhRmlsZXMiOnsiTWVkaWFGaWxlIjp7Il9kZWxpdmVyeSI6InByb2dyZXNzaXZlIiwiX3dpZHRoIjoiNDgwIiwiX2hlaWdodCI6IjMyMCIsIl90eXBlIjoidmlkZW8vbXA0IiwiX19jZGF0YSI6Imh0dHBzOi8vY3JlYXRpdmVjZG4ubW9iZm94LmNvbS82NjAzMzY2YmZjZGFiMmUyMzYzNTVkNWE2NzE5NDQ4Ny5tcDQifX19LCJfc2VxdWVuY2UiOiIxIiwiX2lkIjoiMSJ9fX0sIl9pZCI6IjEifSwiX3ZlcnNpb24iOiIyLjAifX1d","options":{"s":"80187188f458cfde788d961b6882fd53","o_andadvid":"7ec77a58-d504-4fca-b296-c09da6d2c40f","rt":"android_app","adspace_width":320,"adspace_height":480,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","dev_js":1,"banner_pos":7,"dev_dnt":0,"latitude":37.421998333333335,"longitude":-122.08400000000002,"imp_secure":0,"r_type":"video","r_resp":"vast20","v_api":"vpaid20","u":"Mozilla\/5.0 (Linux; Android 7.0; Android SDK built for x86 Build\/NYC; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/51.0.2704.90 Mobile Safari\/537.36","c_customevents":"1","imp_instl":1,"v_autoplay":1,"v_startmute":0,"width":320,"height":480,"skip":true,"start_muted":false,"autoplay":true,"encoded":true},"cacheables":["https:\/\/creativecdn.mobfox.com\/6603366bfcdab2e236355d5a67194487.mp4"],"type":"video"}
07-28 15:23:08.972 2836-2836/com.veblr.videomate D/MobFoxInterstitial: on ad resp

For banner ad which got loaded for two times 
1st one 

07-28 15:55:49.050 16164-16164/com.veblr.videomate E/EXCEPTION: timeout
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err: java.lang.Exception: timeout
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
07-28 15:55:49.051 16164-16164/com.veblr.videomate W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
07-28 15:55:55.052 16164-16164/com.veblr.videomate D/MobFoxBanner: request params: {"s":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","o_andadvid":"","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":1}

2nd one 
07-28 15:55:37.438 16164-16164/com.veblr.videomate D/MobFoxWebView: mobfox webview init
07-28 15:55:37.609 16164-16164/com.veblr.videomate D/MobFoxUtils: read setting
07-28 15:55:37.609 16164-16164/com.veblr.videomate D/MobFoxBanner: dmp post completed
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.bannerads.Banner$2.call(Banner.java:376)
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.runnables.Timeout.mobFoxRun(Timeout.java:30)
07-28 15:55:49.050 16164-16164/com.veblr.videomate W/System.err:     at com.mobfox.sdk.runnables.MobFoxRunnable.run(MobFoxRunnable.java:23)
07-28 15:55:55.052 16164-16164/com.veblr.videomate D/MobFoxBanner: request params: {"s":"ce293de0b1f479b8080e83ba192730a0","o_andadvid":"","type":"waterfall","adFormat":"banner","autoplay":"true","skip":"","debug":"","rt":"android_app","adspace_width":320,"adspace_height":49,"adspace_strict":0,"sub_bundle_id":"com.veblr.videomate","auto_pilot":true,"v":"Core_3.2.7b","secure":false,"start_muted":false,"dev_js":1,"banner_pos":1,"dev_dnt":1}
07-28 15:55:55.965 16164-16164/com.veblr.videomate D/MobFoxBanner: err
07-28 15:55:59.509 16164-16164/com.veblr.videomate D/MobFoxWebView: ready

**Comment by sushrita** [comment]
Hi Itamar 
 I have now tested the `interstitial.setInventoryHash("80187188f458cfde788d961b6882fd53");` code and it's working and I have also tested the banner inventory hashes in my code which were given in demo app it is also working but when I am using my own inventory hash the errors still persists.
So I think there is some problem with my InventoryHash .so can you check it on your end what may be the issue?

**Comment by nabriski** [comment]
Hi,

If the test hash works the integration is done. With a live hash you will not have a 100% fill and usually much less then that until you send enough traffic.

Regards,
Itamar

**Comment by sushrita** [comment]
Hi Itamar,
Is there any specific approach or any documentation regarding how much traffic should be sent to get a particular ad for our app?
And here you are saying we can't have any code for our hash until we make it live or approved , right?

**Comment by nabriski** [comment]
Hi,

No, there isn't. This very much depends on the type of traffic you send.
Yes, you are correct. If it's not approved you will not get any live traffic. After it's approved you will usually have to go live to see the actual fill you will get.

Regards,
Itamar

**Comment by nabriski** [comment]
Please try with 3.6.0 this part was refactored and tested.
