### ISSUE TITLE
MobFox is adding location to permissions by default

### ISSUE THREAD

**Issue by ParkerK** [mobfox/MobFox-Android-SDK#62]
>Added from the MobFox-Android-SDK-Core:3.2.7b manifest, line 10

My app doesn't use location, and I'm not comfortable asking my users for their location. So with the latest MobFox SDK, I can no longer use MobFox, as the `.jar` is injecting location permissions without me telling it to :(

**Comment by nabriski** [comment]
Hi,

Our manifest is no supposed to have this permission. We will check the issue and release an update.

**Comment by brachil** [comment]
Please upgrade to version 3.2.7d.
Thanks.
