### ISSUE TITLE
[Request] Change Logs / Release Notes

### ISSUE THREAD

**Issue by ParkerK** [mobfox/MobFox-Android-SDK#64]
Just a suggestion, it would be nice if change logs / release notes were available so we know what the changes are when the SDK is updated. 

For example, https://github.com/mobfox/MobFox-Android-SDK/releases just says "minor fix", instead of mentioning nice changes like fixing permissions or adding Android O support :)

Thanks!

**Comment by nabriski** [comment]
Hi,

Yes, you are correct, we'll do it better from now on.
