### ISSUE TITLE
Self opening web pages with automatic 5€ subsrciption

### ISSUE THREAD

**Issue by belandsoft** [mobfox/MobFox-Android-SDK#7]
I have a big problem with my app, i received a lot of e-mail from users thet claims automatically open web pages and automatic subscription for 5€ at week!!!!!!! I tried myself and found that sometime it happens!!! I don't want this kind of things in my app! A web page MUST OPEN ONLY IF THE BANNER IS CLICKED, NEVER DO IT AUTOMATICALLY!!!!

YOU MUST FIX THIS BUG NOW!

**Comment by rivir99** [comment]
where do i access the porn i was subscribed to?

**Comment by nabriski** [comment]
Didn't get the last comment, but we now scan the demand for malicious ads so these kind of problems should not happen anymore.
