### ISSUE TITLE
How to create am banner programmatically with 3.6 ???? Constructor broken! Please help!

### ISSUE THREAD

**Issue by wharnisch** [mobfox/MobFox-Android-SDK#74]
Constructor of Banner has changed.

New constructor seams to use be Banner(Context, AttributeSet, int): This constructor throws an Exception when AttributeSet is null. SO HOW CAN I CREATE A BANNER PROGRAMMATICALLY

It would be very nice to have AT LEAST JAVADOC when changing API!!!

**Comment by nabriski** [comment]
Hi,

Not sure that we ever had this documented properly as not many publishers work with us like that. Sorry about that, we're refactoring our docs anyway (to be out in a few weeks) and I'll include it.
As for the CTOR this is what you're looking for:
```java
 public Banner(Context con, int w, int h, String invh, Listener listener) 
```
w -width in pixels, h - height in pixels

Regards,
Itamar

**Comment by wharnisch** [comment]
Hi, thank you very much, this constructor works for me.

The method Banner.setLoc(boolean) no longer exists. Is there a replacement for this so that I can determine whether banners access location or not?

Regards,
Werner

**Comment by nabriski** [comment]
Hi,

No need, now we only access location if your app has the permissions AND has prompted the user. We'll never prompt on our own.
