### ISSUE TITLE
MIN SDK 19 ??? 

### ISSUE THREAD

**Issue by neerajmanoharan** [mobfox/MobFox-Android-SDK#75]
Why has the sdk moved the MIN SDK up to 19 in the new version ?
We have lot of users at lower versions also .
Is there any specific reasons for that, also any methods to bypass it ?

**Comment by nabriski** [comment]
Hi,

We wanted to use some more advanced APIs to improve the SDK and according to the Google Dashboards -  https://developer.android.com/about/dashboards/ - only about 5% of users are using a versions lower than 4.4 (API 19). We reasoned this will not have a large impact on our publishers as this number is low and will continue to go down. I guess you can use the previous version for now (3.5.0) as it still supports lower APIs.

Regards,
Itamar

**Comment by neerajmanoharan** [comment]
Cool.. Thanks for the quick response. (Y)
