### ISSUE TITLE
Please check API Version in Admob Adapter

### ISSUE THREAD

**Issue by wharnisch** [mobfox/MobFox-Android-SDK#76]
We use Mobfox-Android-SDK and Admob Adapter in our apps, but these require API 19, our Apps only require API 14. When using Mobfox-Android-SDK directly we can check API version before requesting an app and prevent requesting if API<19. Problem is that Admob Adapter crashes App if App runs on API 18 for example. This could be prevented simply by checking API version in Admob Adapter and just returning an error or no fill if API<19.

**Comment by nabriski** [comment]
Good idea. We'll implement this and try to release it quickly, early next week.

**Comment by nabriski** [comment]
Hi,

Ok, I'm starting to test this. Can you please share with me your setup so I can test more efficiently?
Are you using our JAR installation?

Thanks

**Comment by wharnisch** [comment]
This is from my build.gradle:

api 'com.github.mobfox.MobFox-Android-SDK-Core:MobFox-Android-SDK-Core:3.6.0'
api files('libs/MobFox-Android-AdMob-Adapter-3.6.0.jar')

If I can get a new version of MobFox-Android-AdMob-Adapter-3.6.0.jar I could also test and give feedback.

**Comment by nabriski** [comment]
Sure, will post it here tomorrow morning.

**Comment by nabriski** [comment]
Here:
http://static.starbolt.io/admob-adapter-for-lower-apis-RC1.jar

**Comment by wharnisch** [comment]
No more crashes on API 18, looks good!

**Comment by nabriski** [comment]
Thanks! I'll release it properly later today or tomorrow morning at latest.

**Comment by nabriski** [comment]
Hi,
Tested and uploaded to the repo, also changed the adapters in our latest release 3.6.0 to have this fix.
