### ISSUE TITLE
Issues with upgrade to 3.6.x

### ISSUE THREAD

**Issue by andre-arsenault** [mobfox/MobFox-Android-SDK#78]
Hello. I know you mentioned there are breaking changes in 3.6.0 and I have reviewed all available documentation. I am still having a few problems getting my code to compile. I am using a custom Cordova plugin-in, and so using the SDK natively and programatically.

I have two problems:

**1. Banner Listeners**

Previous code used to instantiate banner listeners like this:
`BannerListener mBannerListener = new BannerListener()`

Now, of course, it must be done by using `Banner.Listener()` instead.
**What data type does `Banner.Listener()` return and where do we import it from?**

**2. GDPR Support**

I see we can follow the instructions at the [bottom of this page](https://mobfox.atlassian.net/wiki/spaces/PUMD/pages/354451655/Integrate+via+Android+SDK) to add the following code instead of calling `banner.setGdpr()` and `banner.setGdprConsent()`:
```
MobfoxRequestParams mfrp = new MobfoxRequestParams();
mfrp.setParam(MobfoxRequestParams.GDPR, gdpr);
mfrp.setParam(MobfoxRequestParams.GDPR_CONSENT,gdpr_consent);
 
// add gdpr param to banner
banner.addParams(mfrp);
 
// add gdpr param to interstitial
interstitial.setRequestParams(mfrp);
```

**How do we import `MobfoxRequestParams`?**
I tried `import com.sdk.mobfox.MobfoxRequestParams;` but that isn't a valid symbol.

**Comment by nabriski** [comment]
Hi,

1. The listener is defined inside the Banner class as:
```java
public interface Listener {
        void onBannerError(Banner banner, Exception e);
        void onBannerLoaded(Banner banner);
        void onBannerClosed(Banner banner);
        void onBannerFinished();
        void onBannerClicked(Banner banner);
        void onNoFill(Banner banner);
    }
```
Can be imported as
```java
import com.mobfox.sdk.banner.Banner;
```

2. The ```MobfoxRequestParams``` can be imported as:
```java
import com.mobfox.sdk.networking.MobfoxRequestParams;
```

**Comment by andre-arsenault** [comment]
Thank you, that got me far enough along to resolve those two issues. The change in the Listener interface meant I had to update all of those `@Override` methods because they used to take a `View` as their first parameter.

Importing the Listener interface was done with: `import com.mobfox.sdk.banner.Banner.Listener;`

Cool.

So now I only have compile issues with my own CustomEvent adapter for Amazon:

```
...\platforms\android\src\Amazon.java:23: error: Amazon is not abstract and does not override abstract method setListener(CustomEventBannerListener) in CustomEventBanner

public class Amazon extends DefaultAdListener implements CustomEventBanner {
```

From that I can infer that there is a new method that needs to be implemented. **Do you have any guidance or a reference implementation of `CustomEventBanner.setListener`?**

It seems that `CustomEventBanner.loadAd` still provides a `CustomEventBannerListener` in its second parameter, so why and when is the new `setListener` method called?

I can't refer to your example implementation because the [documentation for Writing Custom Events](https://mobfox.atlassian.net/wiki/spaces/PUMD/pages/354451655/Integrate+via+Android+SDK) hasn't been updated.

Cheers.

**Comment by nabriski** [comment]
Hi,

I apologize for that, we only regularly update the MoPub and AdMob custom events.
I'm opening an internal issue for the Amazon custom event and it will be ready next week.

Here is the implementation for MoPub if it helps in the mean time:
```java
package com.mobfox.sdk.customevents;

import android.content.Context;
import android.text.TextUtils;
import android.util.Log;
import android.widget.FrameLayout;

import com.mobfox.sdk.utils.LayoutUtils;
import com.mopub.mobileads.MoPubErrorCode;
import com.mopub.mobileads.MoPubView;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by asafg84 on 19/10/16.
 * Custom event for moPub
 */
public class MoPub implements CustomEventBanner {

    private static String TAG = "MoPubCustomEvent";
    CustomEventBannerListener listener ;

    @Override
    public void loadAd(final Context context, final CustomEventBannerListener listener, final String networkID, final Map<String, Object> params) {
        Log.d(TAG, "MobFox MoPub Custom >> loadAd");
        this.listener = listener;
        MoPubView moPubView = new MoPubView(context);

        int width;
        int height;
        try {

            Integer hi = (Integer) params.get("height");
            Integer wi = (Integer) params.get("width");
            height = LayoutUtils.convertDpToPixel(hi.floatValue(),context);
            width  = LayoutUtils.convertDpToPixel(wi.floatValue(),context);

            List<String> keyWordsList = new ArrayList<String>();

            //adView.keywords = @"m_age:24,m_gender:m,m_marital:single";
            if(params.containsKey("demo_age")){
                keyWordsList.add("m_age:"+params.get("demo_age").toString().toLowerCase());
            }
            if(params.containsKey("demo_gender")){
                keyWordsList.add("m_gender:"+params.get("demo_gender").toString().toLowerCase());
            }

            if(keyWordsList.size() > 0){
                moPubView.setKeywords(TextUtils.join(",",keyWordsList));
            }

            FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(width,height);
            moPubView.setLayoutParams(layoutParams);

        } catch (Exception e) {
            Log.e(TAG, "MobFox MoPub Custom >> error", e);
            listener.onBannerError(moPubView, e);
            return;
        }

        final MoPub self = this;
        moPubView.setAdUnitId(networkID);
        moPubView.setBannerAdListener(new MoPubView.BannerAdListener() {
            @Override
            public void onBannerLoaded(MoPubView banner) {
                Log.d(TAG, "MobFox MoPub Custom >> loaded");
                self.listener.onBannerLoaded(banner);
            }

            @Override
            public void onBannerFailed(MoPubView banner, MoPubErrorCode errorCode) {
                Log.e(TAG, "MobFox MoPub Custom >> error");
                self.listener.onBannerError(banner, new Exception("errorCode: " + errorCode));
            }

            @Override
            public void onBannerClicked(MoPubView banner) {
                Log.d(TAG, "MobFox MoPub Custom >> clicked");
                self.listener.onBannerClicked(banner);
            }

            @Override
            public void onBannerExpanded(MoPubView banner) {
                Log.d(TAG, "MobFox MoPub Custom >> expanded");
            }

            @Override
            public void onBannerCollapsed(MoPubView banner) {
                Log.d(TAG, "MobFox MoPub Custom >> collapsed");
                self.listener.onBannerClosed(banner);
            }
        });
        moPubView.loadAd();
    }

    @Override
    public void setListener(CustomEventBannerListener listener) {
        this.listener = listener;
    }
}
```

**Comment by nabriski** [comment]
Sorry, didn't see it was your own Custom Event (we do not support Amazon in custom events). Guess the code will help you anyway.
We'll update our custom events docs.

**Comment by andre-arsenault** [comment]
I'm up and running now, thanks! Your implementation of `CustomEventBanner.setListener` is as expected.

A few hours of my time would have been saved if your team had specified in the release notes what the breaking changes were, instead of just saying "there are breaking changes, please read the documentation to find them." I'd have a much better developer experience with good release notes. :) At the moment I rather dread your SDK updates.

Thank you for the quick responses. I'm glad you're trying to keep the documentation up to date, it helps a lot. Might I suggest you add an obvious link to the Confluence site's documentation in the README.md? It was a bit difficult for me to find.

**Comment by nabriski** [comment]
Thanks for the feedback, we'll improve on this, especially in the release notes.
