### ISSUE TITLE
audio sound from banner ads ?

### ISSUE THREAD

**Issue by weakapp** [mobfox/MobFox-Android-SDK#79]
Hi.
Some of our users recently reported that there are audio sound from banner ads.
We are using admob mediation and try to find out which network ads cause this issue.
When it happens, we always the messages from mobfox.
We can't reproduce this issue so we can't get full trace.
Anyway we can send request with 'mute' parameter or we can do anything to check this ?

**Comment by nabriski** [comment]
Hi,

Best is a network log but as you say you can't get it at the moment. If you have something recent and give me the inventory id, device type, ad size, country and the time it happened I can try and find it in our db and disable this demand.
There is not 'mute' param, only for video demand.

Thanks

**Comment by weakapp** [comment]
Hi.

inventory id: 6220dd2b02898e033fe4bfc4834be4b8
device type: Samsung S8
ad size: 320x50
country: unknown
time: around 9:30 pm UTC-7 (today)

Weakapp

小說閱讀器/輕鬆讀小說粉絲團: http://goo.gl/v6jhjY
Twitter: @weakapp


Itamar Nabriski <notifications@github.com> 於 2018年8月30日 週四 下午2:43寫道：

**Comment by weakapp** [comment]
Hi.

country is *Seattle, US*

小說閱讀器/輕鬆讀小說粉絲團: http://goo.gl/v6jhjY
Twitter: @weakapp


W Weakapp <weakapp@gmail.com> 於 2018年8月30日 週四 下午2:47寫道：

**Comment by nabriski** [comment]
Too much data ... can you please provide me with the Google Advertising ID connected with the device (GAID)?

Thanks

**Comment by weakapp** [comment]
Hi.

See the attachment.


Itamar Nabriski <notifications@github.com> 於 2018年8月30日 週四 17:36 寫道：

**Comment by nabriski** [comment]
Hi,

Were is this attachment?

**Comment by weakapp** [comment]
你好。

Google Advertising ID  you requested ？

Weakapp

Itamar Nabriski <notifications@github.com> 於 2018年9月1日 週六 05:54 寫道：

**Comment by nabriski** [comment]
The Google Advertising ID is a uuid made from hexadecimals (IFA), this is what I mean:
https://help.tune.com/marketing-console/finding-your-android-device-identifiers/

**Comment by weakapp** [comment]
Hi.

I just tested to use My Tune app to get google advertise id and it is the
same as the screenshot we sent to you.


Weakapp


Itamar Nabriski <notifications@github.com> 於 2018年9月1日 週六 17:56 寫道：

**Comment by nabriski** [comment]
Hi,

Sorry, I don't see the screenshot here, can you please paste it again?

**Comment by weakapp** [comment]
Hi.

See the advertise id.
Thanks.

Itamar Nabriski <notifications@github.com> 於 2018年9月2日 週日 00:26 寫道：

**Comment by nabriski** [comment]
Hi,

There is some misunderstanding here, I don't see any photo attached here or text. Maybe try and send it to my email at itamar.n@mobfox.com?

Thanks

**Comment by nabriski** [comment]
continued thread via email.
